backend:
  name: git-gateway
  branch: main
collections:
  - name: "movies"
    label: "الأفلام"
    folder: "movies"
    create: true
    fields:
      - {label: "اسم الفيلم", name: "title", widget: "string"}
      - {label: "صورة الفيلم", name: "image", widget: "image"}
      - {label: "رابط المشاهدة", name: "link", widget: "string"}

